language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - master

# cache this directory
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
#  - git config --global user.name "leesipeng"
#  - git config --global user.email "leesipeng@gmail.com"
 - openssl aes-256-cbc -K $encrypted_8476227931e4_key -iv $encrypted_8476227931e4_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
 - chmod 600 ~/.ssh/id_rsa
 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa
 - cp .travis/ssh_config ~/.ssh/config
#  - npm install -g hexo-cli # 安装 hexo
#  - git clone https://github.com/leesipeng/hexo-theme-even.git themes/even

install:
  - npm install # 安装 package.json 中的插件

script:
  # - hexo clean
  # - hexo generate

after_success:
  - ssh root@101.132.35.8 -p 22 'cd /usr/local/src/ && git pull'
  # - tar -jcf chat-wall-node.tar.bz2 * # 打包并压缩代码
  # - scp chat-wall-node.tar.bz2 root@101.132.35.8:~/ # 复制到生产服务器上
  # - ssh root@101.132.35.8 'mkdir -p chat-wall-node && tar -jxf chat-wall-node.tar.bz2 -C chat-wall-node' # 解压
  # - ssh root@101.132.35.8 'cd chat-wall-node && pm2 startOrReload pm2.json' # 重启pm2
# E: Build LifeCycle